# Generated by Django 4.0 on 2023-01-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campos',
            fields=[
                ('campo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(default=False, max_length=50)),
                ('media', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.CharField(default=False, max_length=50)),
                ('Descripcion', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('torneo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo_de_torneo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default=False, max_length=100)),
                ('ApellidoPaterno', models.CharField(default=False, max_length=100)),
                ('Birthday', models.DateField()),
                ('Curp', models.CharField(default=False, max_length=100)),
                ('equipo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vistas.equipo')),
                ('user_rol_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vistas.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_arbitro', to='vistas.users')),
                ('campos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_campos', to='vistas.campos')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_entrenador', to='vistas.equipo')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_local', to='vistas.equipo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_status_torneo', to='vistas.torneo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_toreno', to='vistas.torneo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_visitante', to='vistas.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='liguilla',
            fields=[
                ('id_liguilla', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_liga', models.DateField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('partidos_enpatados', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_enccontra', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('type_torneo', models.IntegerField()),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_equipo_stadisticas', to='vistas.equipo')),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_torneo', to='vistas.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id_amonestacion', models.AutoField(primary_key=True, serialize=False)),
                ('minuto', models.CharField(default=False, max_length=20)),
                ('origen', models.CharField(default=False, max_length=20)),
                ('equipo_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.equipo')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.partidos')),
            ],
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_arbitro_campo', to='vistas.users')),
                ('id_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_jugador', to='vistas.users')),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.partidos')),
            ],
        ),
    ]
