# Generated by Django 4.0 on 2022-11-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('ApellidoPaterno', models.CharField(max_length=200)),
                ('Curp', models.CharField(max_length=200)),
                ('Brithday', models.CharField(max_length=200)),
            ],
        ),
    ]
