# Generated by Django 4.0 on 2022-11-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Campos',
            fields=[
                ('campo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(default=False, max_length=50)),
                ('media', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id_amonestacion', models.AutoField(primary_key=True, serialize=False)),
                ('minuto', models.CharField(default=False, max_length=20)),
                ('origen', models.CharField(default=False, max_length=20)),
                ('equipo_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.CharField(default=False, max_length=50)),
                ('Descripcion', models.CharField(default=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('torneo_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('Equipo', models.ManyToManyField(to='vistas.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default=False, max_length=100)),
                ('ApellidoPaterno', models.CharField(default=False, max_length=100)),
                ('Birthday', models.DateField()),
                ('Curp', models.CharField(default=False, max_length=100)),
                ('equipo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vistas.equipo')),
                ('user_rol_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vistas.rol')),
            ],
        ),
        migrations.DeleteModel(
            name='Tabla_test',
        ),
        migrations.AddField(
            model_name='partidos',
            name='arbitro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_arbitro', to='vistas.users'),
        ),
        migrations.AddField(
            model_name='partidos',
            name='campos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_campos', to='vistas.campos'),
        ),
        migrations.AddField(
            model_name='partidos',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_entrenador', to='vistas.equipo'),
        ),
        migrations.AddField(
            model_name='partidos',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_local', to='vistas.equipo'),
        ),
        migrations.AddField(
            model_name='partidos',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_status_torneo', to='vistas.torneo'),
        ),
        migrations.AddField(
            model_name='partidos',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_toreno', to='vistas.torneo'),
        ),
        migrations.AddField(
            model_name='partidos',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_visitante', to='vistas.equipo'),
        ),
        migrations.AddField(
            model_name='gol',
            name='id_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.partidos'),
        ),
        migrations.AddField(
            model_name='amonestacion',
            name='id_arbitro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_arbitro_campo', to='vistas.users'),
        ),
        migrations.AddField(
            model_name='amonestacion',
            name='id_jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_jugador', to='vistas.users'),
        ),
        migrations.AddField(
            model_name='amonestacion',
            name='id_partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vistas.partidos'),
        ),
    ]
