# Generated by Django 4.0 on 2022-11-06 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0002_amonestacion_campos_equipo_gol_partidos_rol_torneo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='liguilla',
            fields=[
                ('id_liguilla', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_liga', models.DateField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('partidos_enpatados', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_enccontra', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('type_torneo', models.IntegerField()),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_equipo_stadisticas', to='vistas.equipo')),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_torneo', to='vistas.torneo')),
            ],
        ),
    ]
