# Generated by Django 4.0 on 2022-11-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rol', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='Brithday',
            field=models.DateTimeField(),
        ),
    ]
